DROP TABLE Employee CASCADE;
DROP TABLE Residence CASCADE;
DROP TABLE Person CASCADE;
DROP TABLE Facility CASCADE;
DROP TABLE Vaccine CASCADE;
DROP TABLE Infection CASCADE;
DROP TABLE Employment CASCADE;
DROP TABLE Residency CASCADE;